-- MySQL Script generated by MySQL Workbench
-- Wed Jan 21 19:45:25 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema travel_agency
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema travel_agency
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `travel_agency` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `travel_agency` ;

-- -----------------------------------------------------
-- Table `travel_agency`.`tourpackages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `travel_agency`.`tourpackages` ;

CREATE TABLE IF NOT EXISTS `travel_agency`.`tourpackages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(225) NOT NULL,
  `price` VARCHAR(225) NULL DEFAULT NULL,
  `duration` VARCHAR(225) NULL DEFAULT NULL,
  `image_path` VARCHAR(225) NULL DEFAULT NULL,
  `address` VARCHAR(225) NULL DEFAULT NULL,
  `phone` VARCHAR(50) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `travel_agency`.`city_locations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `travel_agency`.`city_locations` ;

CREATE TABLE IF NOT EXISTS `travel_agency`.`city_locations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `location_name` VARCHAR(225) NOT NULL,
  `duration` INT NULL DEFAULT NULL,
  `image_path` VARCHAR(225) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `tourpackage_id` INT NULL DEFAULT NULL,
  `price` VARCHAR(225) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `tourpackage_id_idx` (`tourpackage_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `travel_agency`.`hotel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `travel_agency`.`hotel` ;

CREATE TABLE IF NOT EXISTS `travel_agency`.`hotel` (
  `hotel_id` INT NOT NULL AUTO_INCREMENT,
  `hotel_name` VARCHAR(100) NULL DEFAULT NULL,
  `hotel_location` VARCHAR(100) NULL DEFAULT NULL,
  `room_stock` INT NULL DEFAULT NULL,
  `photo_path` VARCHAR(500) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `phone_number` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`hotel_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `travel_agency`.`hotel_reservations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `travel_agency`.`hotel_reservations` ;

CREATE TABLE IF NOT EXISTS `travel_agency`.`hotel_reservations` (
  `reservation_id` INT NOT NULL AUTO_INCREMENT,
  `customer_name` VARCHAR(100) NOT NULL,
  `hotel_id` INT NOT NULL,
  `category_name` VARCHAR(255) NOT NULL,
  `check_in` DATE NOT NULL,
  `check_out` DATE NOT NULL,
  `status` VARCHAR(50) NOT NULL DEFAULT 'null',
  PRIMARY KEY (`reservation_id`),
  INDEX `hotel_id` (`hotel_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `travel_agency`.`logtable`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `travel_agency`.`logtable` ;

CREATE TABLE IF NOT EXISTS `travel_agency`.`logtable` (
  `userid` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`userid`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `password_UNIQUE` (`password` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `travel_agency`.`package_bookings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `travel_agency`.`package_bookings` ;

CREATE TABLE IF NOT EXISTS `travel_agency`.`package_bookings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `address` TEXT NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `booking_date` VARCHAR(50) NULL DEFAULT NULL,
  `start_date` VARCHAR(50) NULL DEFAULT NULL,
  `member` INT NOT NULL,
  `package` INT NULL DEFAULT NULL,
  `status` ENUM('pending', 'done', 'approved', 'rejected') NOT NULL DEFAULT 'pending',
  PRIMARY KEY (`id`, `member`),
  INDEX `package_idx` (`package` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `travel_agency`.`room_stock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `travel_agency`.`room_stock` ;

CREATE TABLE IF NOT EXISTS `travel_agency`.`room_stock` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hotel_id` INT NOT NULL,
  `category_name` VARCHAR(255) NOT NULL,
  `available_room` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `hotel_id` (`hotel_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
